### ISSUE TITLE
The download link is currently empty.

### ISSUE THREAD

**Issue by Yiqingde** [WHU-USI3DV/WHU-Railway3D#1]
Hello, the download link is currently empty. I am eagerly looking forward to the early release of the Railway3D data as it will be of great help to me!

**Comment by QB-1314** [comment]
> Hello, the download link is currently empty. I am eagerly looking forward to the early release of the Railway3D data as it will be of great help to me!

Dear Yiqingde:
Thank you very much for your interest in our work!
I'm sorry for the late reply. The urban railway dataset that has been published and the datasets for the other two scenes will be made available in subsequent releases. For more information on how to use our dataset, it is recommended to refer to the answer on  #3.
If you encounter any further issues or have additional questions, please feel free to reach out. 
Best regards,

**Comment by JulesSanchez** [comment]
Hello, urban and plateau railway dataset are not empty (train folder at least), but rural is. Any release date to communicate ?

Best,
