### ISSUE TITLE
All Zero 3D Coordinates in Uploaded Data

### ISSUE THREAD

**Issue by ccl-1** [WHU-USI3DV/WHU-Railway3D#3]
Hello, thanks for your contribution to the railway community by providing the WHU-Railway3D dataset. However, upon downloading the dataset from the Baiduyun version, I encountered several issues that I believe need attention.
1.	All Zero 3D Coordinates in Uploaded Data. when I started working with it, I noticed that all the 3D coordinates are 0.I double checked my code with other .ply data and it works fine. But when it comes to this dataset, all outputs are 0.
2.	Another thing I noticed – the data I requested only has training stuff for urban railways, but no labels. Just wondering if there are any plans to upload corrected data with labels and release another 2 sets of data.

**Comment by QB-1314** [comment]
> Hello, thanks for your contribution to the railway community by providing the WHU-Railway3D dataset. However, upon downloading the dataset from the Baiduyun version, I encountered several issues that I believe need attention.
> 
> 1. All Zero 3D Coordinates in Uploaded Data. when I started working with it, I noticed that all the 3D coordinates are 0.I double checked my code with other .ply data and it works fine. But when it comes to this dataset, all outputs are 0.
> 2. Another thing I noticed – the data I requested only has training stuff for urban railways, but no labels. Just wondering if there are any plans to upload corrected data with labels and release another 2 sets of data.

Dear stickerB-),
Thank you very much for your interest in our work! Regarding the two points you raised, I will address them in detail:

1. Concerning the urban railways dataset, I have carefully checked the uploaded .ply data and have read it using a Python script. So far, I have not encountered the coordinate issue you mentioned. Have you attempted visualizing the downloaded point cloud data using tools such as CloudCompare? During my visualization checks, I found the uploaded data to be normal and accompanied by semantic labels. As for the issue with all three-dimensional coordinates being zero, it may require you to review your code again. Additionally, you may consider using the .ply file reading and writing functions provided by the author of KPConv to process our dataset. The script link is: [https://github.com/HuguesTHOMAS/KPConv/blob/master/utils/ply.py](https://github.com/HuguesTHOMAS/KPConv/blob/master/utils/ply.py). 

You can download this script to your project directory, and an example code for reading our .ply data is provided as follows:
`
import os, glob
import numpy as np
from ply import read_ply

dataset_path = '/path/to/your/dataset'

for pc_path in glob.glob(os.path.join(dataset_path, '*.ply')):
    print('dealing with file : ', pc_path)
    data = read_ply(pc_path)
    xyz = np.vstack((data['x'], data['y'], data['z'])).T
    labels = np.array(data['class'])
    labels = labels.reshape(np.size(labels, 0), 1)
    intensity = np.array(data['intensity'])
    intensity = intensity.reshape(np.size(intensity, 0), 1)
    print('xyz.shape = ', xyz.shape)
    print('labels.shape = ', labels.shape)
    print('intensity.shape = ', intensity.shape)
    print('xyz[0:10] = ', xyz[0:10])
    print('labels[0:10] = ', labels[0:10])
    print('intensity[0:10] = ', intensity[0:10])
    print('successfully load file : ', pc_path)
    exit()
`

2. The urban railway dataset that has been published includes labels, with the corresponding attribute in the .ply file being 'class'. Furthermore, we have plans to release datasets for the remaining two scenes. Currently, the paper is still undergoing peer review, and the datasets for the other two scenes will be made available in subsequent releases.

If you encounter any further issues or have additional questions, please feel free to reach out. Thank you for your continued interest in our work!

Best regards,
