### ISSUE TITLE
About 3D Object Detection

### ISSUE THREAD

**Issue by rubbish001** [WHU-USI3DV/WHU-Railway3D#4]
看看我的工程，吊打目前所有的3D目标检测
哈哈
https://github.com/rubbish001/Co-Fix3d

中稿就提供训练日志

**Comment by QB-1314** [comment]
> 看看我的工程，吊打目前所有的3D目标检测 哈哈 https://github.com/rubbish001/Co-Fix3d
> 
> 中稿就提供训练日志

感谢你对我们项目的关注和支持。

3D目标检测是很重要的研究领域，铁路场景的3D目标检测也是很有应用价值的方向，如果你感兴趣的话，可以考虑开展相关研究，期待未来有机会和你进行合作或交流！

如果对我们的项目有任何具体问题或建议，也非常欢迎您的反馈。

预祝论文顺利接收！
