### ISSUE TITLE
Paper available 

### ISSUE THREAD

**Issue by JulesSanchez** [WHU-USI3DV/WHU-Railway3D#5]
Is there a link for the paper without institutionnal access ?
I'd be very interested in the acquisition process and setup in detail.

Thank you for your work,

Jules

**Comment by boqiuphd** [comment]
> Is there a link for the paper without institutionnal access ? I'd be very interested in the acquisition process and setup in detail.
> 
> Thank you for your work,
> 
> Jules

Thank you for your interest in our work! Please leave your e-mail and I will send you the paper.

**Comment by JulesSanchez** [comment]
I have trouble finding your email address,
if you could email me at jules.n.sanchez@gmail.com
