### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by ClosedOn** [WHU-USI3DV/WHU-Railway3D#7]
I noticed an error during the training process: ValueError: attempt to get argmin of an empty sequence, and it seems that the data preprocessing script does not include the test data preprocessing part?
![微信图片_20241028174458](https://github.com/user-attachments/assets/114e0cae-3f47-4610-b491-9acecec1add8)

**Comment by boqiuphd** [comment]
This may require you to make appropriate changes to the preprocessing scripts to resolve this issue. It is also recommended to move all PLY data from the training, validation, and test sets to the same path for preprocessing. For example, you could put all the .ply files for urban railways in a folder named '/urban_railways'.
