### ISSUE TITLE
AttributeError: ‘Railway3DDataset’ object has no attribute ‘validation_split’

### ISSUE THREAD

**Issue by pping0412** [WHU-USI3DV/WHU-Railway3D#8]
Hello Professor, I haav some problems with training and visualization: 
Q1:AttributeError: ‘Railway3DDataset’ object has no attribute ‘validation_split’,subsequently I changed this line of code to: if val_loader.dataset.val_file_name not in val_loader.dataset.all_file_name: .
<img width="626" alt="1731288434000" src="https://github.com/user-attachments/assets/64cdc1ee-d0b3-44e0-8ecb-c74f2ff30fac">
Q2:Error when running visualisation code:I ndexError: list index out of range
![1731401447488](https://github.com/user-attachments/assets/00094fc1-8ee4-4e87-96c0-6a690a2efba2)

**Comment by boqiuphd** [comment]
> Hello Professor, I haav some problems with training and visualization: 
> Q1:AttributeError: ‘Railway3DDataset’ object has no attribute ‘validation_split’,subsequently I changed this line of code to: if val_loader.dataset.val_file_name not in val_loader.dataset.all_file_name.
> Q2:Error when running visualisation code:I ndexError: list index out of range.

Thank you for your interest in our work!

A1: Your training phase is fine, but the error occurs during the validation phase. Please check if the value of `self.val_paths` in `Railway3D.py` is correct, and verify whether the validation data has been correctly loaded into the DataLoader.

A2: I have not encountered a similar error before, and with the limited information you provided, I cannot pinpoint the exact cause of the issue. You might consider asking ChatGPT or Copilot for assistance.
